---
apiVersion: v1
kind: Secret
metadata:
  name: wind-wind-turbine-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-connect/wind-wind-turbine-gitops
